In [1]:
# importing libraries in order to use its functions like numpy, pandas, matplotlib

import numpy as np
import pandas as pd
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.patches as mpatches
import matplotlib.mlab as mlab

## This function takes the size of the structure plus mean and standard deviation. It then produces a normal distribution based on mean and standard deviation. The number of hits that each block needs requires is determined by that normal distribution. So, it inserts random values from that normal distribution to the array of size(x,y,z) which is passed as an argument in this function.

In [2]:
# Defining a function which takes size of an array i.e (x,y,z) plus mean and standard deviation.
def blockmodel(x,y,z,mu,sigma):
    
    #generating normal distribution from mean and standard deviation.
    #Also, then inserting random numbers from that distribution into array of size (x,y,z)
    a=np.random.normal(mu, sigma, (x,y,z))
    
    #converting the values in the array to int because hits that each block takes can't be floats. 
    #and then returning the array.
    return a.astype(int)

In [3]:
sample=blockmodel(2,3,4,5,0.5)
print(sample)
print(sample.shape)

[[[5 4 4 5]
  [5 4 5 5]
  [5 5 5 4]]

 [[4 4 4 3]
  [4 5 4 5]
  [4 4 5 5]]]
(2, 3, 4)
